#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-avro
Version  : 1.8.2
Release  : 3
URL      : https://github.com/apache/avro/archive/release-1.8.2.tar.gz
Source0  : https://github.com/apache/avro/archive/release-1.8.2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/avro/avro/1.8.2/avro-1.8.2.jar
Source2  : https://repo1.maven.org/maven2/org/apache/avro/avro/1.8.2/avro-1.8.2.pom
Summary  : C library for parsing Avro data
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 MIT
Requires: mvn-avro-data = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : buildreq-distutils3

%description
NAME
Avro - official Perl API for the Avro serialization and RPC framework
SYNOPSIS
use Avro;

%package data
Summary: data components for the mvn-avro package.
Group: Data

%description data
data components for the mvn-avro package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2/avro-1.8.2.jar
/usr/share/java/.m2/repository/org/apache/avro/avro/1.8.2/avro-1.8.2.pom
